### ISSUE TITLE
Multitabs

### ISSUE THREAD

**Issue by vezhevich** [maxdenaro/maxgraph-youtube-source#11]
Если на странице необходимо реализовать несколько блоков с табами, существующий код под это не рассчитан?

**Comment by Maxxxtj** [comment]
Я пока учусь, пробую что-то делать. Такую задачу перед собой пока не ставил

**Comment by maxdenaro** [comment]
> Если на странице необходимо реализовать несколько блоков с табами, существующий код под это не рассчитан?

Да, не рассчитан.
